export type ContractArea = "health" | "admin" | "auth" | "device" | "execution" | "provider" | "telemetry" | "support" | "internal";
export type ContractSource = "worker.fetch" | "usage-counter.fetch";
export type ContractShape = "json-object" | "json-array" | "html" | "text" | "empty" | "sse";
export type ContractSetup = "none" | "device" | "admin-populated" | "profile-apply" | "profile-draft" | "profile-publish" | "profile-rollback";
export type AdminCapability = "view" | "edit" | "publish";

export type ContractFixture = {
  id: string;
  area: ContractArea;
  source: ContractSource;
  method: "GET" | "POST" | "PUT" | "OPTIONS";
  path: string;
  adminCapability?: AdminCapability;
  setup?: ContractSetup;
  request: {
    contentType?: string;
    headers?: Record<string, string>;
    body?: unknown;
    bodyFactory?: () => BodyInit;
    bodyKind?: "json" | "text" | "multipart";
  };
  response: {
    status: number | number[];
    contentType: "application/json" | "text/html" | "text/plain" | "empty" | "missing" | "text/event-stream";
    shape: ContractShape;
    requiredKeys?: string[];
    errorCodes?: string[];
  };
  mockedProviderCalls?: number;
  notes?: string;
};

export type NonHttpContractFixture = {
  id: string;
  source: "worker.scheduled";
  notes: string;
};

export const CONTRACT_TEST_VALUES = {
  deviceId: "fixture-device-001",
  alternateDeviceId: "fixture-device-002",
  installId: "fixture-install-001",
  oauthState: "fixture-oauth-state-001",
  oauthToken: "fixture-oauth-token-001",
  providerKey: "fixture-provider-key-001",
  transcript: "synthetic-transcript-sentinel-001",
  selectedText: "synthetic-selection-sentinel-001",
  audio: "synthetic-audio-sentinel-001",
  accountId: "fixture-account-001",
  providerRequestId: "fixture-provider-request-001",
} as const;

const ADMIN_ORIGIN = "https://admin.fixture.test";
const ADMIN_HEADERS = {
  Origin: ADMIN_ORIGIN,
};

function jsonRequest(body: unknown, options: Partial<ContractFixture["request"]> = {}): ContractFixture["request"] {
  return {
    contentType: "application/json",
    bodyKind: "json",
    body,
    ...options,
  };
}

function getRequest(options: Partial<ContractFixture["request"]> = {}): ContractFixture["request"] {
  return { ...options };
}

function adminJsonRequest(body: unknown, options: Partial<ContractFixture["request"]> = {}): ContractFixture["request"] {
  return jsonRequest(body, { headers: ADMIN_HEADERS, ...options });
}

function adminGetRequest(options: Partial<ContractFixture["request"]> = {}): ContractFixture["request"] {
  return getRequest({ headers: ADMIN_HEADERS, ...options });
}

function jsonResponse(
  status: number | number[] = 200,
  requiredKeys: string[] = [],
  errorCodes: string[] = [],
): ContractFixture["response"] {
  return {
    status,
    contentType: "application/json",
    shape: "json-object",
    requiredKeys,
    errorCodes,
  };
}

function errorResponse(
  status: number | number[],
  errorCodes: string[] = [],
): ContractFixture["response"] {
  return jsonResponse(status, ["error"], errorCodes);
}

export const HTTP_CONTRACT_FIXTURES: readonly ContractFixture[] = [
  {
    id: "health",
    area: "health",
    source: "worker.fetch",
    method: "GET",
    path: "/health",
    request: getRequest(),
    response: jsonResponse(200, ["ok", "service", "date"]),
  },
  {
    id: "control-plane-admin-page",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/control-plane-admin",
    request: getRequest(),
    response: { status: 200, contentType: "text/html", shape: "html" },
    notes: "Legacy embedded Control Plane page; Admin Web is the preferred authenticated surface.",
  },
  {
    id: "admin-options-cors",
    area: "admin",
    source: "worker.fetch",
    method: "OPTIONS",
    path: "/admin/control-plane/policy",
    request: {
      headers: {
        ...ADMIN_HEADERS,
        "Access-Control-Request-Method": "GET",
        "Access-Control-Request-Headers": "authorization,content-type",
      },
    },
    response: { status: 204, contentType: "empty", shape: "empty" },
  },
  {
    id: "admin-dashboard-summary",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/dashboard/summary",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["today", "last7d", "topModels7d", "recentErrors"]),
  },
  {
    id: "admin-request-events",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/requests?limit=5",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["items", "nextCursor"]),
  },
  {
    id: "admin-usage-summary",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/usage/summary?limit=5",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["today", "last7d", "byDay"]),
  },
  {
    id: "admin-feedback-list",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/feedback?limit=5",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["items", "nextCursor"]),
  },
  {
    id: "admin-runtime-policy",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/control-plane/policy",
    adminCapability: "view",
    setup: "admin-populated",
    request: adminGetRequest(),
    response: jsonResponse(200, ["ok", "source", "updatedAt", "policy", "defaultPolicy"]),
  },
  {
    id: "admin-profiles-list",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/control-plane/profiles",
    adminCapability: "view",
    setup: "admin-populated",
    request: adminGetRequest(),
    response: jsonResponse(200, ["ok", "schemaVersion", "updatedAt", "profiles"]),
  },
  {
    id: "admin-profile-audit",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/control-plane/audit",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["schemaVersion", "records"]),
  },
  {
    id: "admin-profile-preview",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/control-plane/profiles/preview?profileId=pro",
    adminCapability: "view",
    setup: "profile-draft",
    request: adminGetRequest(),
    response: jsonResponse(200, ["profileId", "draftVersion", "activeVersion", "diff", "warnings", "impact", "selectedTarget", "pricing"], ["profile_projection_unavailable"]),
  },
  {
    id: "admin-role-resolve",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/control-plane/roles/resolve?bootstrapOwnerEmail=owner%40fixture.test&principalKey=fixture-principal",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["role"]),
  },
  {
    id: "admin-role-list",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/control-plane/roles?bootstrapOwnerEmail=owner%40fixture.test",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["bindings"]),
  },
  {
    id: "admin-role-set",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/roles",
    adminCapability: "edit",
    request: adminJsonRequest({
      bootstrapOwnerEmail: "owner@fixture.test",
      actorEmail: "owner@fixture.test",
      subjectEmail: "editor@fixture.test",
      role: "editor",
    }),
    response: jsonResponse(200, ["bindings"]),
  },
  {
    id: "admin-role-remove",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/roles/remove",
    adminCapability: "edit",
    request: adminJsonRequest({
      bootstrapOwnerEmail: "owner@fixture.test",
      actorEmail: "owner@fixture.test",
      subjectEmail: "editor@fixture.test",
    }),
    response: jsonResponse(200, ["bindings"]),
  },
  {
    id: "admin-profile-draft-create",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/profiles/drafts",
    adminCapability: "edit",
    request: adminJsonRequest({ profileId: "pro" }),
    response: jsonResponse(200, ["profileId", "draft"]),
  },
  {
    id: "admin-profile-apply",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/profiles/apply",
    adminCapability: "publish",
    setup: "profile-apply",
    request: adminJsonRequest({
      profileId: "pro",
      expectedActiveVersion: 1,
      definition: { label: "Fixture profile apply" },
      confirmation: "APPLY pro v1",
    }),
    response: jsonResponse(200, ["profileId", "label", "published", "draft", "history"]),
    notes: "Runs against a fresh in-memory profile snapshot prepared by the fixture harness only.",
  },
  {
    id: "admin-profile-publish",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/profiles/publish",
    adminCapability: "publish",
    setup: "profile-publish",
    request: adminJsonRequest({
      profileId: "pro",
      expectedActiveVersion: 1,
      expectedDraftVersion: 2,
      confirmation: "PUBLISH pro v2",
    }),
    response: jsonResponse(200, ["profileId", "published", "history"]),
    notes: "Runs against a fresh in-memory profile snapshot prepared by the fixture harness only.",
  },
  {
    id: "admin-profile-rollback",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/profiles/rollback",
    adminCapability: "publish",
    setup: "profile-rollback",
    request: adminJsonRequest({
      profileId: "pro",
      version: 1,
      expectedActiveVersion: 2,
      confirmation: "ROLLBACK pro to v1",
    }),
    response: jsonResponse(200, ["profileId", "published", "history"]),
    notes: "Runs against a fresh in-memory profile snapshot prepared by the fixture harness only.",
  },
  {
    id: "admin-devices-list",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/control-plane/devices?limit=5",
    adminCapability: "view",
    setup: "admin-populated",
    request: adminGetRequest(),
    response: jsonResponse(200, ["ok", "source", "updatedAt", "policyOptions", "devices", "nextCursor"]),
  },
  {
    id: "admin-device-policy",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/devices/policy",
    adminCapability: "edit",
    setup: "device",
    request: adminJsonRequest({ deviceId: CONTRACT_TEST_VALUES.deviceId, policyId: "pro" }),
    response: jsonResponse(200, ["ok", "device", "policyOptions"]),
  },
  {
    id: "admin-accounts-list",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/control-plane/accounts?limit=5",
    adminCapability: "view",
    setup: "admin-populated",
    request: adminGetRequest(),
    response: jsonResponse(200, ["ok", "source", "updatedAt", "policyOptions", "accounts", "nextCursor"]),
  },
  {
    id: "admin-account-policy",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/accounts/policy",
    adminCapability: "edit",
    request: adminJsonRequest({ accountHandle: "acc_fixture_missing", policyId: "pro" }),
    response: errorResponse([404, 400], ["account_not_found"]),
  },
  {
    id: "admin-account-budget",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/accounts/budget",
    adminCapability: "edit",
    request: adminJsonRequest({ accountHandle: "acc_fixture_missing", budget: { dailyUsd: 1, monthlyUsd: 5, mode: "warn" } }),
    response: errorResponse([404, 400], ["account_not_found"]),
  },
  {
    id: "admin-account-groups",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/accounts/groups",
    adminCapability: "edit",
    request: adminJsonRequest({ accountHandle: "acc_fixture_missing", groups: ["friends"] }),
    response: errorResponse([404, 400], ["account_not_found"]),
  },
  {
    id: "admin-account-segments",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/accounts/segments",
    adminCapability: "edit",
    request: adminJsonRequest({ accountHandle: "acc_fixture_missing", segments: ["fixture-segment"] }),
    response: errorResponse([404, 400], ["account_not_found"]),
  },
  {
    id: "admin-account-variants-assign",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/accounts/variants/assign",
    adminCapability: "edit",
    request: adminJsonRequest({ accountHandle: "acc_fixture_missing", variants: ["trial"] }),
    response: errorResponse([404, 400], ["account_not_found"]),
  },
  {
    id: "admin-groups-create",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/groups",
    adminCapability: "edit",
    request: adminJsonRequest({ id: "fixture-group", label: "Fixture Group", description: "Provider-free contract fixture", policyId: "pro" }),
    response: jsonResponse(200, ["ok", "group", "groupOptions"]),
  },
  {
    id: "admin-account-variant-create",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/accounts/variants",
    adminCapability: "edit",
    request: adminJsonRequest({ id: "fixture-variant", label: "Fixture Variant", description: "Provider-free contract fixture", preset: "custom" }),
    response: jsonResponse(200, ["ok", "variant", "variantOptions", "availableSegments"]),
  },
  {
    id: "admin-account-variant-delete",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/accounts/variants/delete",
    adminCapability: "edit",
    request: adminJsonRequest({ id: "fixture-variant" }),
    response: jsonResponse(200, ["ok", "variant", "variantOptions", "availableSegments"]),
  },
  {
    id: "admin-policy-variants",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/policy/variants",
    adminCapability: "edit",
    request: adminJsonRequest({ policyId: "pro", variants: ["trial"] }),
    response: jsonResponse(200, ["ok", "source", "updatedAt", "policyVariants", "policyEngines", "policyBudgets"]),
  },
  {
    id: "admin-policy-engines-read-only-conflict",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/policy/engines",
    adminCapability: "edit",
    request: adminJsonRequest({ policyId: "pro", engine: "fixture-engine" }),
    response: errorResponse(409, ["profile_composer_required"]),
  },
  {
    id: "admin-policy-budget-read-only-conflict",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/policy/budget",
    adminCapability: "edit",
    request: adminJsonRequest({ policyId: "pro", dailyUsd: 1 }),
    response: errorResponse(409, ["profile_composer_required"]),
  },
  {
    id: "admin-selection-preset-defaults",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/policy/selection-presets",
    adminCapability: "edit",
    request: adminJsonRequest({
      source: "fixvox-cloud-admin",
      items: [{
        id: "fixture-preset",
        label: "Fixture Preset",
        promptId: "preset.fixture",
        hotkey: "Alt+T, F",
        pickerKey: "F",
        provider: "groq",
        model: null,
        enabled: true,
        confirm: false,
        promptContent: "Fixture preset prompt.",
      }],
    }),
    response: jsonResponse(200, ["ok", "source", "updatedAt", "profileOptions", "variantOptions", "engineOptions", "promptOptions"]),
  },
  {
    id: "admin-engine-create",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/engines",
    adminCapability: "edit",
    request: adminJsonRequest({ id: "fixture-engine", label: "Fixture Engine", kind: "transcription", tier: "fixture", provider: "groq", model: "fixture-model", promptKey: "none" }),
    response: jsonResponse(200, ["ok", "engine", "engineOptions"]),
  },
  {
    id: "admin-engine-delete",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/engines/delete",
    adminCapability: "edit",
    request: adminJsonRequest({ id: "fixture-engine" }),
    response: jsonResponse(200, ["ok", "engine", "engineOptions"]),
  },
  {
    id: "admin-prompt-create",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/prompts",
    adminCapability: "edit",
    request: adminJsonRequest({ id: "fixture-prompt", label: "Fixture Prompt", kind: "assistant", version: "v1", summary: "Fixture", content: "Provider-free prompt fixture." }),
    response: jsonResponse(200, ["ok", "prompt", "promptOptions"]),
  },
  {
    id: "admin-prompt-delete",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/prompts/delete",
    adminCapability: "edit",
    request: adminJsonRequest({ id: "fixture-prompt" }),
    response: jsonResponse(200, ["ok", "prompt", "promptOptions"]),
  },
  {
    id: "admin-runtime-policy-put",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/policy",
    adminCapability: "edit",
    request: adminJsonRequest({ runtimeMode: "local" }),
    response: jsonResponse(200, ["ok", "updatedAt", "policy"]),
  },
  {
    id: "admin-runtime-policy-reset",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/policy/reset",
    adminCapability: "edit",
    request: adminJsonRequest({}),
    response: jsonResponse(200, ["ok", "updatedAt", "policy"]),
  },
  {
    id: "admin-recipe-policy-get",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/control-plane/recipe-policy",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["ok", "source", "updatedAt", "policy", "defaultPolicy"]),
  },
  {
    id: "admin-recipe-policy-put",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/recipe-policy",
    adminCapability: "edit",
    request: adminJsonRequest({ version: "fixture", defaultRecipeId: "dictation", recipes: [], contextMappings: [] }),
    response: jsonResponse(200, ["ok", "updatedAt", "policy"]),
  },
  {
    id: "admin-recipe-policy-reset",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/control-plane/recipe-policy/reset",
    adminCapability: "edit",
    request: adminJsonRequest({}),
    response: jsonResponse(200, ["ok", "updatedAt", "policy"]),
  },
  {
    id: "admin-provider-models",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/control-plane/models?provider=groq",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["ok", "provider", "source", "configured", "llmModels", "speechModels", "error"]),
    mockedProviderCalls: 1,
  },
  {
    id: "admin-pricing-get",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/pricing",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["watchlist", "pricing"]),
  },
  {
    id: "admin-pricing-watchlist",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/pricing/watchlist",
    adminCapability: "edit",
    request: adminJsonRequest({ targets: [] }),
    response: jsonResponse(200, ["watchlist", "pricing"]),
  },
  {
    id: "admin-pricing-refresh",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/pricing/refresh",
    adminCapability: "edit",
    request: adminJsonRequest({}),
    response: jsonResponse(200, ["watchlist", "pricing"]),
  },
  {
    id: "admin-discord-config",
    area: "admin",
    source: "worker.fetch",
    method: "GET",
    path: "/admin/discord/config",
    adminCapability: "view",
    request: adminGetRequest(),
    response: jsonResponse(200, ["ok", "applicationIdConfigured", "botTokenConfigured", "publicKeyConfigured", "interactionEndpoint", "commands"]),
  },
  {
    id: "admin-discord-sync-commands",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/discord/sync-commands",
    adminCapability: "edit",
    request: adminJsonRequest({}),
    response: errorResponse(500),
    notes: "Provider-free configuration failure; the route must not attempt Discord when credentials are absent.",
  },
  {
    id: "admin-discord-scan-support",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/discord/scan-support",
    adminCapability: "edit",
    request: adminJsonRequest({}),
    response: jsonResponse(200, ["ok", "scannedChannels", "repliedMessageIds"]),
  },
  {
    id: "admin-benchmark-chat",
    area: "admin",
    source: "worker.fetch",
    method: "POST",
    path: "/admin/benchmark/chat/completions",
    adminCapability: "edit",
    request: adminJsonRequest({ model: "fixture-model", stream: false, messages: [{ role: "user", content: "fixture benchmark" }] }),
    response: jsonResponse(200, ["id", "choices"]),
    mockedProviderCalls: 1,
  },
  {
    id: "discord-interaction-invalid-signature",
    area: "support",
    source: "worker.fetch",
    method: "POST",
    path: "/discord/interactions",
    request: jsonRequest({ type: 1 }),
    response: { status: 401, contentType: "missing", shape: "text" },
    notes: "Current signature failure is plain text and is intentionally frozen as an observed compatibility gap.",
  },
  {
    id: "telegram-webhook-disabled",
    area: "support",
    source: "worker.fetch",
    method: "POST",
    path: "/telegram/webhook",
    request: jsonRequest({ update_id: 1 }),
    response: jsonResponse(200, ["ok", "platform", "enabled", "handled", "reason"]),
  },
  {
    id: "device-register",
    area: "device",
    source: "worker.fetch",
    method: "POST",
    path: "/v2/device/register",
    request: jsonRequest({
      installId: CONTRACT_TEST_VALUES.installId,
      deviceId: CONTRACT_TEST_VALUES.deviceId,
      version: "0.1.0-fixture",
      platform: "windows",
      arch: "x64",
      hostname: "fixture-host",
    }),
    response: jsonResponse(200, ["ok", "deviceId", "activated", "auth", "features", "defaults", "limits", "telemetry"]),
  },
  {
    id: "device-activate",
    area: "device",
    source: "worker.fetch",
    method: "POST",
    path: "/v2/device/activate",
    request: jsonRequest({
      installId: "fixture-install-activate",
      deviceId: CONTRACT_TEST_VALUES.alternateDeviceId,
      inviteCode: "FIXTURE-BASIC",
      version: "0.1.0-fixture",
      platform: "windows",
      arch: "x64",
    }),
    response: jsonResponse(200, ["ok", "deviceId", "activated", "policyId", "policyLabel"], ["invite_code_required"]),
  },
  {
    id: "execution-preflight",
    area: "execution",
    source: "worker.fetch",
    method: "POST",
    path: "/v2/execution/preflight",
    setup: "device",
    request: jsonRequest({
      mode: "managed",
      deviceId: CONTRACT_TEST_VALUES.deviceId,
      installId: CONTRACT_TEST_VALUES.installId,
      usageKind: "managed",
      engineKind: "transcription",
      estimate: 1,
    }),
    response: jsonResponse(200, ["ok", "allowed", "reason", "limits", "profile", "engines"], ["service_unavailable", "device_not_registered", "quota_exceeded"]),
  },
  {
    id: "telemetry-events-batch",
    area: "telemetry",
    source: "worker.fetch",
    method: "POST",
    path: "/v2/telemetry/events/batch",
    request: jsonRequest({ installId: CONTRACT_TEST_VALUES.installId, sentAt: "2026-01-01T00:00:00.000Z", events: [{ id: "fixture-event-001" }] }),
    response: jsonResponse(200, ["ok", "acceptedIds", "received"]),
  },
  {
    id: "feedback-submit",
    area: "telemetry",
    source: "worker.fetch",
    method: "POST",
    path: "/v2/feedback/submit",
    request: jsonRequest({ type: "idea", source: "contract-fixture", message: "fixture feedback", deviceId: CONTRACT_TEST_VALUES.deviceId, installId: CONTRACT_TEST_VALUES.installId, loggedIn: false }),
    response: jsonResponse(200, ["ok", "id", "ts"]),
  },
  {
    id: "desktop-login-start",
    area: "auth",
    source: "worker.fetch",
    method: "GET",
    path: "/desktop/login?flow=device-code&client=fixvox-tauri&state=fixture-oauth-state-001",
    request: getRequest(),
    response: { status: 200, contentType: "text/html", shape: "html" },
    notes: "The state is accepted by the desktop protocol but must never appear in operator evidence or rendered HTML.",
  },
  {
    id: "desktop-login-invalid",
    area: "auth",
    source: "worker.fetch",
    method: "GET",
    path: "/desktop/login?flow=unknown&client=fixvox-tauri",
    request: getRequest(),
    response: errorResponse(400),
  },
  {
    id: "desktop-google-start-missing-handoff",
    area: "auth",
    source: "worker.fetch",
    method: "GET",
    path: "/desktop/google/start?handoff=fixture-missing-handoff",
    request: getRequest(),
    response: { status: 200, contentType: "text/html", shape: "html" },
  },
  {
    id: "desktop-login-status-missing",
    area: "auth",
    source: "worker.fetch",
    method: "GET",
    path: "/desktop/login/status?state=fixture-oauth-state-missing",
    request: getRequest(),
    response: errorResponse(404),
  },
  {
    id: "desktop-link-device-missing-state",
    area: "auth",
    source: "worker.fetch",
    method: "POST",
    path: "/desktop/login/link-device",
    request: jsonRequest({ installId: CONTRACT_TEST_VALUES.installId, deviceId: CONTRACT_TEST_VALUES.deviceId }),
    response: errorResponse(400),
  },
  {
    id: "google-auth-start-json",
    area: "auth",
    source: "worker.fetch",
    method: "GET",
    path: "/auth/google/start?device_id=fixture-device-001&code_verifier=fixture-code-verifier-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&mode=json",
    request: getRequest(),
    response: jsonResponse(200, ["ok", "state", "authorizeUrl", "redirectUri"]),
    notes: "OAuth state is intentionally returned to the client protocol and redacted only in evidence.",
  },
  {
    id: "google-auth-result-missing",
    area: "auth",
    source: "worker.fetch",
    method: "GET",
    path: "/auth/google/result?state=fixture-oauth-state-missing&device_id=fixture-device-001",
    request: getRequest(),
    response: errorResponse(404),
  },
  {
    id: "google-callback-missing-state",
    area: "auth",
    source: "worker.fetch",
    method: "GET",
    path: "/callback",
    request: getRequest(),
    response: { status: 200, contentType: "text/html", shape: "html" },
  },
  {
    id: "chat-completions",
    area: "provider",
    source: "worker.fetch",
    method: "POST",
    path: "/v1/chat/completions",
    setup: "device",
    request: jsonRequest({ model: "fixture-request-model", stream: false, messages: [{ role: "user", content: CONTRACT_TEST_VALUES.selectedText }] }, {
      headers: {
        "X-Device-Id": CONTRACT_TEST_VALUES.deviceId,
        "X-Fixvox-Request-Context": "selection",
      },
    }),
    response: jsonResponse(200, ["id", "choices"]),
    mockedProviderCalls: 1,
    notes: "The upstream provider is replaced with a deterministic in-memory response; exactly one call is expected.",
  },
  {
    id: "usage-prewarm",
    area: "execution",
    source: "worker.fetch",
    method: "POST",
    path: "/v1/usage/prewarm",
    setup: "device",
    request: getRequest({ headers: { "X-Device-Id": CONTRACT_TEST_VALUES.deviceId } }),
    response: jsonResponse(200, ["ok", "deviceId", "replace", "voice", "timing"]),
  },
  {
    id: "audio-transcriptions",
    area: "provider",
    source: "worker.fetch",
    method: "POST",
    path: "/v1/audio/transcriptions",
    setup: "device",
    request: {
      contentType: "multipart/form-data",
      bodyKind: "multipart",
      headers: {
        "X-Device-Id": CONTRACT_TEST_VALUES.deviceId,
        "X-Audio-Duration": "1",
      },
      bodyFactory: () => {
        const form = new FormData();
        form.set("file", new Blob([new TextEncoder().encode(CONTRACT_TEST_VALUES.audio)], { type: "audio/wav" }), "fixture.wav");
        form.set("model", "whisper-large-v3-turbo");
        return form;
      },
    },
    response: jsonResponse(200, ["text"]),
    mockedProviderCalls: 1,
    notes: "Audio is synthetic and only exists in the request fixture; it must not occur in storage or evidence.",
  },
  {
    id: "unknown-route-error",
    area: "health",
    source: "worker.fetch",
    method: "GET",
    path: "/fixture/not-found",
    request: getRequest(),
    response: errorResponse(404),
  },
  {
    id: "usage-counter-reserve",
    area: "internal",
    source: "usage-counter.fetch",
    method: "POST",
    path: "/reserve",
    request: jsonRequest({ key: "fixture-counter-key", limit: 10, reserve: 2, resetAt: "2099-01-01T00:00:00.000Z" }),
    response: jsonResponse(200, ["ok", "key", "granted", "used", "remaining", "limit", "resetAt"]),
  },
  {
    id: "usage-counter-consume",
    area: "internal",
    source: "usage-counter.fetch",
    method: "POST",
    path: "/consume",
    request: jsonRequest({ key: "fixture-counter-key", limit: 10, amount: 1, resetAt: "2099-01-01T00:00:00.000Z" }),
    response: jsonResponse(200, ["ok", "key", "used", "remaining", "limit", "resetAt"]),
  },
  {
    id: "usage-counter-observe-prewarm",
    area: "internal",
    source: "usage-counter.fetch",
    method: "POST",
    path: "/observe-prewarm",
    request: jsonRequest({ day: "2099-01-01", success: true, observedAt: "2099-01-01T00:00:00.000Z" }),
    response: jsonResponse(200, ["ok"]),
  },
  {
    id: "usage-counter-prewarm-summary",
    area: "internal",
    source: "usage-counter.fetch",
    method: "GET",
    path: "/prewarm-summary",
    request: getRequest(),
    response: jsonResponse(200, ["days"]),
  },
] as const;

export const NON_HTTP_CONTRACT_FIXTURES: readonly NonHttpContractFixture[] = [
  {
    id: "scheduled-maintenance",
    source: "worker.scheduled",
    notes: "Scheduled tasks run with provider credentials absent; no network call is allowed in the fixture harness.",
  },
];

export function fixturePathWithoutQuery(path: string): string {
  return path.split("?", 1)[0] ?? path;
}

export function expectedStatuses(fixture: ContractFixture): number[] {
  return Array.isArray(fixture.response.status) ? fixture.response.status : [fixture.response.status];
}
